'w_rated_me', 'd_me', 'd_hsg', 'r_me', 'r_hsg',
'jp', 'kp', 'dp', 'kt', 'shaft_speed_max',
'omega', 'd_omega', 'time_step', 
'specific_fuel_coeefs_for_main_engine',
'specific_fuel_coeffs_for_dg',
'fuel_cons_me', 'fuel_cons_electrical', 'fuel_cons',
'power_me', 'power_hsg', 'me_rated', 'hsg_rated',
'load_hist', 'fuel_rate_me', 'fuel_rate_hsg',
'fuel_me', 'fuel_hsg', 'fuel', 'fuel_rate',
'load_perc_me', 'load_perc_hsg', 'power_total', 'power_prop'